### ISSUE TITLE
Add banners & integrate with code analysis

### ISSUE THREAD

**Issue by filfreire** [filfreire/CommentCop#14]
- [x] Add mit license banner
- [x] Add qulice banner (created issue on qulice project https://github.com/teamed/qulice/issues/860)
- [x] Add intelliJ
- [x] codeclimate
- [x] https://codecov.io
- [x] https://sonarcloud.io
- [x] http://i.jpeek.org/ (follow-up on issue #21 )
- [x] https://www.codacy.com
- [x] https://codebeat.co
- [x] https://coveralls.io  (having some problems, created follow-up issue #25)
- [x] coverity
- [x] gitter
